name: industrial_ci_rolling

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  schedule:
    - cron: "0 2 * * 0"

jobs:
  ci_rolling :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: rolling
          ROS_REPO: main